package model;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * FilePDFDAOInterface. Provides the interface to FilePDFDAO.
 */

public interface FilePDFDAOInterface {

  /**
   * Insert the pdf file into the database.
   * 
   * @param FilePDF.
   * @return returns the int value of the state generated by the query execution.
   * @throws SQLException.
   */
  public int insertFilePDF(FilePDF file);

  /**
   * Get a set of PDF files given the request id.
   * 
   * @param requestRCID is the id of the Request.
   * @return returns an set of FilePDF related to the Request.
   */
  public ArrayList<FilePDF> doRetrieveAllFilePDFByIDRequestRC(int requestRCID);


}
