package model;

import java.sql.SQLException;
import java.util.ArrayList;

/**
 * FilePDFDAOInterface.
 * Provides the interface to FilePDFDAO.
 */

public interface FilePDFDAOInterface {
	
	/**
	* Insert the pdf file into the database.
	* @param FilePDF.
	* @return returns the int value of the state generated by the query execution.
	* @throws SQLException 
	*/
	public int insertFilePDF(FilePDF file) throws SQLException;
	
	/**
	* Get a set of PDF files given the request id.
	* @param requestRCID is the id of the Request.
	* @return returns an set of FilePDF related to the Request.
	*/
	public ArrayList<FilePDF> doRetrieveAllFilePDFByIDRequestRC(int requestRCID);
	
	/**
	* Get a PDF file given the request and file id.
	* @param requestRCID is the id of the Request.
	* @param PDFID is the id of PDF.
	* @return returns the file that corresponds to the request id and the file id.
	*/
	public FilePDF doRetrieveFilePDF(int requestRCID, int PDFID);
	
}
