package model;

import java.util.ArrayList;

/**
 * ReportDAO.
 *interacts with the database in order 
 *to manage the report data for a prefressa 
 *career recognition request
 */

public class ReportDAO implements ReportDAOInterface {

	/**
	* Insert the Report into the database.
	* @param Report
	* @return returns the int value of the state generated by the query execution.
	*/
	@Override
	public int insertReport(Report report) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	* Update the Report into the database.
	* @param Report
	* @return returns the int value of the state generated by the query execution.
	*/
	@Override
	public int updateReport(Report report) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	* Update the list of validated exams into the database by Report id and the new exam list.
	* @param Report
	* @param validatedExamsList is an arrayList that contains validated Report exams
	* @return returns the int value of the state generated by the query execution.
	*/
	@Override
	public int updateValidatedExamsList(int reportID, ArrayList<ValidatedExam> validatedExamsList) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	* Update the note into the database by report id and the new note.
	* @param reportID is the id of the Report.
	* @param note notes contains the annotations that the PCD has inserted regarding the Report.
	* @return returns the int value of the state generated by the query execution.
	*/
	@Override
	public int updateNote(int reportID, String note) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	* get Report by report id.
	* @param reportID is the id of the Report.
	* @return returns the report that has the id equal to reportID.
	*/
	@Override
	public Report doRetrieveReportByReportID(int reportID) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	* Get the list of validated exams by Report id.
	* @param reportID is the id of the Report..
	* @return returns an set of validated exams related to the report.
	*/
	@Override
	public ArrayList<ValidatedExam> doRetrieveValidatedExamsByReportID(int reportID) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	* Delete Report into the database by Report id.
	* @param reportID is the id of the Report.
	* @return returns the int value of the state generated by the query execution.
	*/
	@Override
	public int deleteReport(int reportID) {
		// TODO Auto-generated method stub
		return 0;
	}

}
